[package]
name = "db-export"
version = "0.1.1"
edition = "2021"

[dependencies]
sqlite = "^0"
flate2 = "^1"
hex = "^0"
tokio = { version = "1", features = ["full"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"